version: "3.9"

services:
  rabbitmq:
    build: 
      context: .
    image: rabbitmq:1.0
    container_name: rabbitmq
    volumes:
      - ./rabbitmq/data/log:/var/log/rabbitmq
      - ./rabbitmq/data/mnesia:/var/lib/rabbitmq/mnesia
    ports:
      - 15672:15672
      - 5672:5672
      - 5552:5552